### ISSUE TITLE
код не работает

### ISSUE THREAD

**Issue by bdu1977** [AlbertGBarber/Coro-Pixel-Star-270#1]
можно получить код для проекта coro-pixel-star? тот код что на github он не дает тех эффектов что на видео. и можно еще схему подключения светодиодов получить

**Comment by AlbertGBarber** [comment]
The code should match the video. Can you be most specific as to what effects are missing (the video has timestamps for each effect). The wiring description is in the Readme.

**Comment by bdu1977** [comment]
у меня вообще нет тех эффектов, что на видео. у меня простое моргание и бегающие точки. саму модель я не собирал, я ее сделал в программе proteus там и смотрел все эффекты с данным кодом. я все модели так проверяю, прежде чем собрать. могу сделать небольшое видео экрана. 
очень хочу собрать такую звезду, но немного поменьше, но с кодом никак не получается.
очень прошу помочь с кодом.

**Comment by bdu1977** [comment]
скорее всего это проблема в библиотеках. изначально я скачал ваши библиотеки и просто каждый файл определил в свою папку и скопировал в папку библиотек arduino но у меня получается какое-то моргание и непонятные эффекты.
потом я удалил эти библиотеки, создал папку PixelStrip в папке с библиотеками к arduino скомпилировал код и у меня появился только один эффект, это заполнение звезды разными цветами и так по кругу, звезда то красная, то синяя, то желтая, но дальне эффектов нет. помогите пожалуйста.

**Comment by AlbertGBarber** [comment]
I have just tested the code on a physical strip using an Arduino Nano (the intended MC). It all works correctly. If you are not using a light sensor makes sure that `lightSensorDisable` is set to true, or it will block effects from running. 

If the code doesn't work on your side, it is likely an issue with your simulation software or library install. Check the official Arduino guide on manual library installation.

I also suggest testing the code on a physical strip. Even a short run of 30 leds will let you verify it is working.

**Comment by bdu1977** [comment]
а вы могли бы мне выслать ваш рабочий код, скомпилированный для arduino nano для pin 4 и и отключенным датчиком освещенности, файл в формате hex?
тогда я смогу точно понять где у меня ошибка

**Comment by AlbertGBarber** [comment]
You can compile the code yourself using the Arduino Ide. I do not know how to convert it to a hex file.

**Comment by bdu1977** [comment]
данный файл делается в arduino ide
sketch - export copmiled binary
но у меня кажется получилось. все эффекты не просмотрел, они отличаются от того что на видео, но многие появились.
вся проблема была в неверном подключении. я сделал из центра по часовой стрелке наружу, а нужно было из вершины по часовой внутрь идти.
но за hex файл все равно буду благодарен

**Comment by AlbertGBarber** [comment]
Oh, just realized my wiring description in the Readme was wrong, it should have been spiraling inward clockwise as you said. I have updated it. Sorry about that!

Not sure why some the effects would be missing, if any are working they all should be. Try looking at the segment set layouts in the code to confirm that they match your physical connections. "ringSegments" should be the most clear, as it is the "stars" arranged in order from outer-most to inner-most.
